### ISSUE TITLE
SonoffLAN unavailable after some time since last update

### ISSUE THREAD

**Issue by kimme1024** [AlexxIT/SonoffLAN#1120]
Since updating to 2023.2, all my devices connected via the SonoffLAN integration become unavailable after some time.
When I reload the integration they become available immediately. It happens both in local and auto-mode.

**Comment by gimli1967** [comment]
> Since updating to 2023.2, all my devices connected via the SonoffLAN integration become unavailable after some time.
> When I reload the integration they become available immediately. It happens both in local and auto-mode.

Same here!

**Comment by papka1974** [comment]
Same for me.

**Comment by gimli1967** [comment]
> Same for me. 2023.2.5. Addon reload solving problem for some time.

yes, true but after a while they become unavailable again

**Comment by snigehere** [comment]
Same issue for me after I installed the latest update - I have 2 sonoff devices - one switch that seems fine and one temperature and humidity sensor that just drops to unavailable.  Reloading the integration brings it back online.  No entries in the system log so I have enabled the debug page to see if it shows anything useful.

**Comment by papka1974** [comment]
Seems devices picked randomly. Have 6 switches. Random count of them could go offline.

**Comment by Tamsy** [comment]
Maybe related to [this](https://github.com/AlexxIT/SonoffLAN/issues/1106) issue report.

**Comment by snigehere** [comment]
There are multiple tickets that describe the same issue
https://github.com/AlexxIT/SonoffLAN/issues/1120
https://github.com/AlexxIT/SonoffLAN/issues/1117
https://github.com/AlexxIT/SonoffLAN/issues/1112
https://github.com/AlexxIT/SonoffLAN/issues/1110

This one has a suggestion on a solution
https://github.com/AlexxIT/SonoffLAN/issues/1112

**Comment by RubenFelix** [comment]
Same here.
Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Sonoff LAN v3.4.0

![image](https://user-images.githubusercontent.com/1507119/221211849-d9016cf3-8499-44c0-98c3-5f18009136b2.png)

**Comment by scg001** [comment]
experiencing exact same issue.
for now it seems that this can be solved by reverting to previous HA release via terminal (ha core update --version 2023.2.4)

**Comment by kimme1024** [comment]
> experiencing exact same issue.
> for now it seems that this can be solved by reverting to previous HA release via terminal (ha core update --version 2023.2.3)

Or reverting to sonoff lan 3.3.0 works as well…

**Comment by scg001** [comment]
> 

That makes more sense. Thanks

**Comment by Yonny24** [comment]
> > experiencing exact same issue.
> > for now it seems that this can be solved by reverting to previous HA release via terminal (ha core update --version 2023.2.3)
> 
> Or reverting to sonoff lan 3.3.0 works as well…

How do you rollback the hacs integration?
Thanks

**Comment by papka1974** [comment]
I tried to switch configuration to "auto" from "local". My switches stopped to became unavailable, but appeared another problem. One of switches lost it's real status within HA. Like it was switched on, but in HA showed as switched off. So I moved back to "local" and checked "default home". Will look how it will works.

**Comment by kimme1024** [comment]
> > > experiencing exact same issue.
> > > for now it seems that this can be solved by reverting to previous HA release via terminal (ha core update --version 2023.2.3)
> > 
> > 
> > Or reverting to sonoff lan 3.3.0 works as well…
> 
> How do you rollback the hacs integration? Thanks

Find the integration in hacs, reinstall, choose older version. Don’t know it by heart but it’s something like that.

**Comment by Yonny24** [comment]
> > > > experiencing exact same issue.
> > > > for now it seems that this can be solved by reverting to previous HA release via terminal (ha core update --version 2023.2.3)
> > > 
> > > 
> > > Or reverting to sonoff lan 3.3.0 works as well…
> > 
> > 
> > How do you rollback the hacs integration? Thanks
> 
> Find the integration in hacs, reinstall, choose older version. Don’t know it by heart but it’s something like that.

Thanks - It didn't screw up your current entities like adding duplicates with a postfix of '_1' or anything?

**Comment by kimme1024** [comment]
> > > > > experiencing exact same issue.
> > > > > for now it seems that this can be solved by reverting to previous HA release via terminal (ha core update --version 2023.2.3)
> > > > 
> > > > 
> > > > Or reverting to sonoff lan 3.3.0 works as well…
> > > 
> > > 
> > > How do you rollback the hacs integration? Thanks
> > 
> > 
> > Find the integration in hacs, reinstall, choose older version. Don’t know it by heart but it’s something like that.
> 
> Thanks - It didn't screw up your current entities like adding duplicates with a postfix of '_1' or anything?

No didn’t change anything besides solving the issue. Obviously it can be different in your usecase.

**Comment by papka1974** [comment]
Went back to 3.3.  It's easy and everything stayed intact. Just do redownload and choose another version. Then reboot. Let's see how it works now. Configured as local and "default home" unchecked.

**Comment by nsacras** [comment]
> Went back to 3.3. It's easy and everything stayed intact. Just do redownload and choose another version. Then reboot. Let's see how it works now. Configured as local and "default home" unchecked.

I'm unnable to redownload or reinstall it! Could you give me step by step tutorial? I'm making anything wrong but cannot understand what! Thanks

**Comment by papka1974** [comment]
> > Went back to 3.3. It's easy and everything stayed intact. Just do redownload and choose another version. Then reboot. Let's see how it works now. Configured as local and "default home" unchecked.
> 
> I'm unnable to redownload or reinstall it! Could you give me step by step tutorial? I'm making anything wrong but cannot understand what! Thanks

Go to HACS, find Sonoff integration, open it, 3 dots on top, select redownload. You'll be able select required version.

**Comment by nsacras** [comment]
Perfect and I'm totally greatfull. It works.

**Comment by Yonny24** [comment]
> > > Went back to 3.3. It's easy and everything stayed intact. Just do redownload and choose another version. Then reboot. Let's see how it works now. Configured as local and "default home" unchecked.
> > 
> > 
> > I'm unnable to redownload or reinstall it! Could you give me step by step tutorial? I'm making anything wrong but cannot understand what! Thanks
> 
> Go to HACS, find Sonoff integration, open it, 3 dots on top, select redownload. You'll be able select required version. ![Screenshot_20230305-120632](https://user-images.githubusercontent.com/60855611/222954313-d89ff56b-9ca4-4489-b563-6d102f5eb48a.png)

thank you! downgraded now

**Comment by thefunkygibbon** [comment]
how do you know what version is installed?  i've "redownloaded" 3.3.0 and other older versions a bunch of times now but the problem still happens sporadically.  i can't seem to tell what version is "currently installed"   it shouldn't be auto updating, but i fear it might be?! (or not downgrading properly)

**Comment by gabriele-latino** [comment]
same problem here, I'm on 3.3 since 2 weeks...

**Comment by thefunkygibbon** [comment]
hey all, a great workaround since this issue doesn't appear to be being worked on,  is to create an automation to monitor a sonoff device and restart the service automatically.  its not a perfect solution but hopefully it should make the devices work for "most" of the time. 
https://github.com/AlexxIT/SonoffLAN/issues/1138#issuecomment-1478580171

**Comment by snigehere** [comment]
Not at all correct --- I included logs and debug in my issue https://github.com/AlexxIT/SonoffLAN/issues/1126 and you just said don't use local and closed the issue.  Local is a valid option - if it is not working then why is it offered?

**Comment by AlexxIT** [comment]
1. I said that I have improved processing LAN problems in the [new release](https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.0)
2. The documentation for the integration has always recommended to use **auto mode**
3. Local mode exists because some users are afraid of clouds.

I hold to the idea that each user can decide for himself what he needs. If he wants NOT to use the recommendations, that's his choice.

**Comment by papka1974** [comment]
> 1. I said that I have improved processing LAN problems in the [new release](https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.0)
> 2. The documentation for the integration has always recommended to use **auto mode**
> 3. Local mode exists because some users are afraid of clouds
> 
> I hold to the idea that each user can decide for himself what he needs. If he wants NOT to use the recommendations, that's his choice.

Problem appeared whenever of mode. I changed from local to auto and problem appeared again. Only fix was to step 1 version back. Still on older version and no problem in any mode.

**Comment by AlexxIT** [comment]
Problem with model local was for @snigehere. Because he attached some debug info to his issue.
What is the problem of this issue no one knows
https://github.com/AlexxIT/SonoffLAN#issues

**Comment by papka1974** [comment]
Yesterday I updated till latest version. So far so good. Before, problem appeared in pretty short time. So keeping fingers crossed. HA also on latest version.
Another thing I did, I fixed IP addresses for all my switches. Only some if them were fixed before. My bad. However, since this was first thing I did trying to fix problem initially, it didn't help at that moment.

**Comment by AlexxIT** [comment]
I'm using Sonoff devices more than three years.
During this time there were no stability problems at all. Ever.
I have one good router. The IPs of the devices are not fixed.
I'm using auto mode. As recommended in docs.
When cloud offline - devices work via LAN.
When Sonoff LAN proto glitches - devices work via cloud.

**Comment by papka1974** [comment]
Fixed IP's i mentioned only as a change of my previous setup. And all was rock stable for me as well till this case. Hope now stability will be back.

**Comment by papka1974** [comment]
And, as I wrote before, problem was not only on "local" mode, but even on "auto".

**Comment by AlexxIT** [comment]
Well. You not provide any debug info, so we can't know what it was.

**Comment by papka1974** [comment]
My bad. Will provide if problem reappear.

**Comment by louispires** [comment]
I have also been having issues with a single Sonoff device becoming unavailable:
![image](https://user-images.githubusercontent.com/8841644/230032989-0a7d5382-86d4-488d-9f7a-b18158d7b75b.png)
[sonoff-dfc5ea70013a088929ae096e491c24ac-Wishbone Gate-fb7fac61d16a0cbe7f17f4c2404e44bb.json.txt](https://github.com/AlexxIT/SonoffLAN/files/11156982/sonoff-dfc5ea70013a088929ae096e491c24ac-Wishbone.Gate-fb7fac61d16a0cbe7f17f4c2404e44bb.json.txt)

The only way to have it appear online again is to either reload the SonoffLan Integration or Reconnect the device to the Wifi.

I am using full Ubiquiti setup, so it is relatively easy to reconnect the device.

The problem is that this is my Main Gate which is used by other people in my House and they have now been locked out a couple of times...

**Comment by snigehere** [comment]
> The problem is that this is my Main Gate which is used by other people in my House and they have now been locked out a couple of times...

I implemented the automation that @thefunkygibbon posted a link to earlier on in this bug report.. it auto restarts the integration if a device goes unavailable.. that said since 3.5 the issue has not happened again

**Comment by AlexxIT** [comment]
@louispires you need to collect debug logs. Or you can disable `mode: local` and use `mode: auto` as recommended in docs

**Comment by louispires** [comment]
Even in Auto this still occurs and the timing is always terrible!

![Screenshot_20230418_124025_Home Assistant](https://user-images.githubusercontent.com/8841644/232753411-68b483f3-5eb9-4ae4-b813-8bce38655b95.jpg)

Ive now enabled Debug logging and I will be posting later today.

**Comment by louispires** [comment]
[error_log-1.txt](https://github.com/AlexxIT/SonoffLAN/files/11266127/error_log-1.txt)

Here are my debug logs
