### ISSUE TITLE
Powr320d energy sensor with wrong state class

### ISSUE THREAD

**Issue by mrsilva1986** [AlexxIT/SonoffLAN#1168]
Hello, i believe I'm not the only one with this issue. 
Since last update the energy sensor is working, thank you so much for your work, but the state class of the sensor Day and Month is defined as measurement. To this sensor be used in the energy panel it needs to be total_increasing.
It actually works if we create a template for this and copy the data from the sensor but there is no need to have extra entities if we already have one. Is it possible to change this data in the repo so it's used as an energy sensor. 

I leave the log message of home assistant for reference.
```
Entity sensor.sonoff_100179ee63_energy_day (<class 'custom_components.sonoff.sensor.XSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.sonoff_100179ee63_energy_month (<class 'custom_components.sonoff.sensor.XSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

Thank you for your hard work.

**Comment by UmairEEE** [comment]
I am also getting this warning frequently with my POWR320D.

2023-04-20 22:00:47.470 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.sonoff_*********_energy_month (<class 'custom_components.sonoff.sensor.XSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by igorsantos07** [comment]
Same here, for the same device - although the sensors do seem to work, at least they show data on it.

![image](https://github.com/AlexxIT/SonoffLAN/assets/532299/8013e02d-49b0-45ae-b7e7-0230f02295ca)

**Comment by adamwylde** [comment]
I also see this, and it prevents the sensor showing data in the energy dashboard.

**Comment by CurryIan** [comment]
I am having the same problem and unknowingly added it as a new issue.

**Comment by AlexxIT** [comment]
Looks like this problem was fixed in march...
https://github.com/AlexxIT/SonoffLAN/commit/3e6a1a6d57f267d226765409df74082c7d06fd60

There just wasn't time for a release

**Comment by mrsilva1986** [comment]
> Looks like this problem was fixed in march... [3e6a1a6](https://github.com/AlexxIT/SonoffLAN/commit/3e6a1a6d57f267d226765409df74082c7d06fd60)
> 
> There just wasn't time for a release

Hi, first of all, thanks for your hard work.

Question, was the fix implemented in the master version? Cause i just reinstalled the master version and the problem is still there. The sensor can't be added cause the class is wrong.
Once again thank you.

**Comment by AlexxIT** [comment]
Are you sure you have master version? Check this code on your hard drive

**Comment by mrsilva1986** [comment]
> Are you sure you have master version? Check this code on your hard drive

I'm pretty sure. But to check i just removed the full folder from my HA and redownloaded again the addon. 
It's impossible to add the sensor day or month to the energy dashboard.
The current energy it's possible to add but the values that are displayed are not the actual values. 
Exemple, my sonoff app says that i have today consumed 0.54kWh. The sensor day in HA also show the same, but the energy sensor that is possible to add to energy dashboard (the current one) gives me in the dashboard a total of 10.41kWh for today.
Can't even figure it out where that values are comming for since the month total right now is 12.26kWh.

**Comment by d1964b** [comment]
I'm running version 3.51. and I still have this problem.

**Comment by jubudu** [comment]
Same problem here with Powr320d.
-Energy Dashboard shows device class unexpected.
- Summation of energy.day  gives a negative total value each night at 00:00:00. This entry can be manually deleted and the energy dash board shows the correct energy consumption.

**Comment by AlexxIT** [comment]
Looks like this problem fixed long time ago
