### ISSUE TITLE
problems after updating till HomeAssistant Core 2024.1.0

### ISSUE THREAD

**Issue by JensJackowski** [AlexxIT/SonoffLAN#1296]
After updating to HomeAssistant Core 2024.1.0 i got a lot of issues with my SONOFF devices. They did simply no longer react. When trying to turn on a switch HomeAssistant performed no action and toggeld the switch to off after a few seconds.

After deinstalling the update and downgrading to HomeAssistant Core 2023.12.4 everything is working like before without any further problems. 

The log files contained no error-messages regarding the Sonoff-lan integration.

**Comment by zac99** [comment]
I have the same situation after updating to 2024.1.0.

**Comment by peregrines2** [comment]
Having the same problem since updating to 2024.1.0. :(

**Comment by t3lmoazevedo** [comment]
Same here, and the energy state is also missing now...

![image](https://github.com/AlexxIT/SonoffLAN/assets/41584793/801abaf5-d4a1-4895-8360-0e46723462a0)

**Comment by mattefox** [comment]
Also status update is broken.
I've  some light and smartplug that after toggle don't update the lovelace User interface.

**Comment by Rehaell** [comment]
+1 here, I've commented the line that was suggested [here](https://github.com/AlexxIT/SonoffLAN/issues/1288#issuecomment-1876688902), to no avail.

**Comment by Gui576** [comment]
Hello,

Same for me after downgrade no issue all is OK, I will try the fix, but I have also an issue with midea Air integration also

**Comment by petebanham** [comment]
Same issue for me too

**Comment by hmmbob** [comment]
Djeez, don't you all check existing issues before creating a new one?

See #1288 and please close this issue.

**Comment by petebanham** [comment]
> Same issue for me too

Fix link above worked for me. Thanks

**Comment by JensJackowski** [comment]
@hmmbob i just wanted to be nice and give feedback. I do not see if it is the exact same issue and if it is described in a way that it does not make it clear to me that i have had the same problem. 

But since problem #1288 can bee solved in the same way (just roll back the update) i agree that it is better to discuss on that topic.

**Comment by t3lmoazevedo** [comment]
The fix above still doesnst work for me...

![image](https://github.com/AlexxIT/SonoffLAN/assets/41584793/064d1c99-8da6-4cf5-b73c-2ddd8946db8d)

**Comment by AlexxIT** [comment]
#1285
