### ISSUE TITLE
toggles broken after HA Core update 2024

### ISSUE THREAD

**Issue by sambolino** [AlexxIT/SonoffLAN#1311]
After core_2024.1.0 update devices (ch4 pro's, mini r3's) became uncontrollable from HA dashboard - when turning on, toggles move to off after 2 seconds, but device stays on. Then it's hard to turn them off, maybe after several tries (toggles still behave the same, no matter what the real state of device is). History doesn't show any of these changes. Everything works fine from ewelink android app.

It's an issue with the update - rolled back to core_2023.12.4 and it works fine again.

**Comment by Piipz** [comment]
Same here. Did not roll back yet (don't really know how to)

**Comment by 80ChevyC10** [comment]
I am having the same issues with Sonoff Mini r2. I have three of them in home assistant and they all seem to be acting slightly different. One switch switch turns off after two seconds in HA but the actual divice does not turn off. If I turn the switch back on in HA and quickly turn it off before the two seconds it will turn off the device. The other dives seem to just be acting randomly. Everything work fin in the eWeLink app though.

**Comment by rdaraujo** [comment]
It should have been fixed in latest release ( v3.5.4 - 2024-01-04 ).
Give it a try.

**Comment by iendicott** [comment]
Yep this has fixed the issue. Thanks for your time.

**Comment by tmb088** [comment]
just updated HA still got the issue @rdaraujo what version is that HA or the addon?  Updated through Hacs but still getting the issue

**Comment by pterodaktil02** [comment]
same  problem   last  ha  and addon

**Comment by samatild** [comment]
This has been fixed on latest version , I can confirm that toggling works in v3.5.4

**Comment by tmb088** [comment]
> This has been fixed on latest version , I can confirm that toggling works in v3.5.4

how do I check my version ?  in hacs no updates are available

**Comment by pterodaktil02** [comment]
> This has been fixed on latest version , I can confirm that toggling works in v3.5.4

I  find  problem -  firmware  was  very old.  After  fw  update all become   ok

**Comment by arikdpc** [comment]
Had to update everything including the sonoff lan hacks integration. it solved it after restart.

**Comment by sambolino** [comment]
works after 3.5.4, thank you!

**Comment by mfrafael** [comment]
I am running the following versions and all devices are still listed as "unavailable". What else should I do?

   "sonoff": {
      "version": "3.5.4",
    "hacs": {
      "version": "1.33.0",

**Comment by rdaraujo** [comment]
I’d suggest restarting the system where HA is running.
Are your devices also unavailable in the eWeLink app?

**Comment by mfrafael** [comment]
> I’d suggest restarting the system where HA is running on. Are your devices also unavailable in the eWeLink app?

They work fine on the mobile app, just not on Home Assistant.
I have restarted the application, reloded, redownloaded... the only thing I haven't done is uninstall it and start over.
Instead, I'm going to restore a backup file from December 2023

**Comment by tmb088** [comment]
> > I’d suggest restarting the system where HA is running on. Are your devices also unavailable in the eWeLink app?
> 
> They work fine on the mobile app, just not on Home Assistant. I have restarted the application, reloded, redownloaded... the only thing I haven't done is uninstall it and start over. Instead, I'm going to restore a backup file from December 2023

I had the same.  I changed the device class to light from fan and worked well (my sliding wasn't working)
![Screenshot_2024-01-09-16-07-47-620_io homeassistant companion android-edit](https://github.com/AlexxIT/SonoffLAN/assets/84038304/ce3b4961-050a-4fd9-9853-0d822c80f9a2)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#issues
