### ISSUE TITLE
Failed to setup : APPID HAS EXPIRED

### ISSUE THREAD

**Issue by Markii2430** [AlexxIT/SonoffLAN#1374]
Hello, all my sonoff devices are now offline because of this error 
appid has expired 
anyone has the same issue?

**Comment by POMIN-163** [comment]
Me too, this has been the problem since the beginning, I don't know what happened.

**Comment by Markii2430** [comment]
@AlexxIT hello sir how to troubleshoot this issue?

**Comment by POMIN-163** [comment]
> @AlexxIT hello sir how to troubleshoot this issue?

The problem was resolved when I deleted the original sonoff from custom_components and decompressed the latest version of the source.

**Comment by wbertoncello** [comment]
I tried several things including re-installing and re-configuring but then i edited the file custom_components/sonoff/core/ewelink/cloud.py with my country code (in my case +54 there was a default contry code +86) and also edited the regioncode (in my case us there was eu by default).  Restarted and everything is now working.

**Comment by StefanoGiu** [comment]
I have the same issue here...
I tried to install latest component, update country code to +39, restart HA several time, but I still have this issue...

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#issues

**Comment by StefanoGiu** [comment]
1)
Sonoff
Version	3.5.4 (c67dc99)
Cloud devices online	0 / 1
Local devices online	1 / 1

2)
Logger: homeassistant.config_entries
Source: XXX\site-packages\homeassistant\config_entries.py:468
First occurred: 09:20:57 (1 occurrences)
Last logged: 09:20:57

Config entry 'XXX@XX' for sonoff integration could not authenticate: appid has expired

3)
2024-04-02 10:20:39.477 WARNING (MainThread) [homeassistant.config_entries] Config entry 'XXXXX@XXXX' for sonoff integration could not authenticate: appid has expired

**Comment by AlexxIT** [comment]
This is not latest version

**Comment by StefanoGiu** [comment]
I installed the latest version... same issue:

Sonoff
Version	3.6.0 (6886372)
Cloud devices online	0 / 1
Local devices online	1 / 1

**Comment by GrinchUA** [comment]
{'error': 407, 'msg': 'the path of request is not allowed with appid:4s1FXKC9FaGfoqXhmXSJneb3qcm1gOak', 'data': {}}

**Comment by StefanoGiu** [comment]
By the way the error message is clear... appid is expired... maybe the code will need to generate and use a new appid ?

**Comment by StefanoGiu** [comment]
I installed HA 2024.4.0... same issue

**Comment by AlexxIT** [comment]
I have another version after install latest release: 3.6.0 (8dd8af9).

This problem is not present for the rest of the users. What countries are you from? Italy and Argentina?

**Comment by StefanoGiu** [comment]
Italy, why? What's wrong with Italy and Argentina?

**Comment by AlexxIT** [comment]
This error only for your servers. I don't know how many servers ewelink uses for their cloud.

**Comment by StefanoGiu** [comment]
How can I fix it then?

**Comment by AlexxIT** [comment]
Maybe buy new app key from ewelink. Just a few thousand dollars.

**Comment by StefanoGiu** [comment]
oh... ok.... so I will need to keep the error, not being able to fix it?

**Comment by AlexxIT** [comment]
I need to find some free time first. Then create an account in your country to repeat the problem. Then look where I can find another working key. Or you can try to do it all yourself.

**Comment by StefanoGiu** [comment]
If you explain me what to do, I can work by myself and then we can fix it together.

I have eWeLink app on the phone, and I also used HTTP Toolkit in the past with Android emulator to sniff some traffic from apps :)

**Comment by karlbreit** [comment]
I had the same problem when logging in with a -91 number. Updated to 3.6 and updated all the other integrations HA wanted me to update, and it works fine now.

**Comment by StefanoGiu** [comment]
I'm on 3.6 and everything is updated now... but still it doesn't work.

Have you modified the code manually?

I just set 1 in those two lines:
custom_components\sonoff\core\ewelink\cloud.py -->    async def login_token(self, token: str, app: int = 1) -> bool:
custom_components\sonoff\core\ewelink\cloud.py -->    async def login(self, username: str, password: str, app=1) -> bool:

**Comment by StefanoGiu** [comment]
Please let me know if I can help fixing it somehow... I have experience in python coding.

**Comment by AlexxIT** [comment]
Perhaps someone with a problem can give me their login/password. You can change your password beforehand or create a new account that has the same error. You can reach me in the Telegram or Discord.

**Comment by StefanoGiu** [comment]
Can you give me your Telegram id ?

**Comment by AlexxIT** [comment]
I can confirm that `app=1` has expired. But this is NOT default appid. Default appid works fine.
