### ISSUE TITLE
I get this error and it doesn't work for me

### ISSUE THREAD

**Issue by Guille-Mas-Coll** [AlexxIT/SonoffLAN#3]
2020-01-21 22:29:05 ERROR (MainThread) [homeassistant.setup] Error during setup of component sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sonoff/__init__.py", line 35, in setup
    config[CONF_PASSWORD])
  File "/config/custom_components/sonoff/utils.py", line 63, in load_devices
    headers = {'Authorization': "Bearer " + resp['at']}
KeyError: 'at'

**Comment by AlexxIT** [comment]
@Guille-Mas-Coll  Possible reasons:

- phone is used instead of email
- only numbers in the password
- devices not on a european server

Which one?

**Comment by Guille-Mas-Coll** [comment]
I do not remember putting the phone in the ewelink account, I have also been looking and I do not see where I can modify or indicate the phone.

**Comment by AlexxIT** [comment]
@Guille-Mas-Coll if the password contains only numbers, it must be quoted

```password: '12345678'```

**Comment by Guille-Mas-Coll** [comment]
now yes, now I have created the sonoff.json file

**Comment by Guille-Mas-Coll** [comment]
> 
> 
> @Guille-Mas-Coll if the password contains only numbers, it must be quoted
> 
> `password: '12345678'`

now yes, now I have created the sonoff.json file

**Comment by Guille-Mas-Coll** [comment]
It would be interesting if all this information appeared in the readme

**Comment by gsdovali** [comment]
I am having the same error. My password had letters and numbers, tried with 123ABC, '123ABC', "123ABC" didn't worked at all, then I changed my password to numbert only 123456, '123456', "123456" I keep getting the same error. I am from Mexico, so my devices are not on European server I guess they are on AMERICAS.

**Comment by AlexxIT** [comment]
@gsdovali I think I fix non Euro server. You may check it

**Comment by Guille-Mas-Coll** [comment]
@gsdovali, as he comments AlexxIT, you can check with the latest update to see if it works

**Comment by gsdovali** [comment]
Ok, it Is working now, I have a RF Bridge with several dolor sensors attached already learned on ewelink app. How do I make them to show on homeassistant?

**Comment by AlexxIT** [comment]
@gsdovali you need use automation with `sonoff.remote` event

```
automation:
- alias: Test RF
  trigger:
    platform: event
    event_type: sonoff.remote
    event_data:
      command: 0
  action:
    service: homeassistant.toggle
    entity_id: remote.sonoff_1000abcdefg
```

**Comment by prasanthmk82** [comment]
So is logging with phone number not working? Will it be added in future?

**Comment by AlexxIT** [comment]
@prasanthmk82 could you check this version?
https://github.com/AlexxIT/SonoffLAN/tree/phone
I add to main if it's work.
In the phone number only numbers without dashes, spaces and pluses?

**Comment by ashoktvm** [comment]
I will try and let you know. For the time being can you tell me how to make the RF bridge work? the RF bridge alone shows up in entity

**Comment by prasanthmk82** [comment]
I will try and let you know. For the time being can you tell me how to make the RF bridge work? the RF bridge alone shows up in entity

**Comment by prasanthmk82** [comment]
Ok. I have tried first to integrate the component through HACS. Thats showed an error. Then i cpasted the sonoff folder inside the zip into custom components folder. But after restarting it shows this message.
![sonoff integration](https://user-images.githubusercontent.com/60357312/74407127-539ada00-4e57-11ea-9a09-0cf6c86c05bf.jpg)

**Comment by AlexxIT** [comment]
@prasanthmk82 need some logs.

Work with RF Bridge described in examples.

**Comment by prasanthmk82** [comment]
2020-02-13 12:46:55 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-02-13 12:46:55 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-02-13 12:46:58 ERROR (MainThread) [homeassistant.setup] Error during setup of component sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sonoff/__init__.py", line 53, in setup
    config[CONF_PASSWORD])
  File "/config/custom_components/sonoff/utils.py", line 64, in load_devices
    region = resp['region']
KeyError: 'region'
2020-02-13 12:47:05 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2020-02-13 12:47:06 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2020-02-13 12:47:06 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2020-02-13 12:47:20 ERROR (MainThread) [hacs] Validation for DSorlov/hasl-platform failed with GitHub returned 404 for https://api.github.com/repos/DSorlov/hasl-platform/git/trees/master.

**Comment by prasanthmk82** [comment]
> @prasanthmk82 need some logs.
> 
> Work with RF Bridge described in examples.

Done as mentioned. And when listening to the event, I found that in a single press itself it is sending the command thrice instead of one

**Comment by AlexxIT** [comment]
@prasanthmk82 can you check phone number again? I add some log info.
https://github.com/AlexxIT/SonoffLAN/tree/phone
Your phone number starts with "+"?

**Comment by prasanthmk82** [comment]
should I give the country code as well. Any particular format to use?
I Can you tell me why pressing a button in RF remote instead of getting the command as pressed once, i am getting it as pressed 4 times. Please help with this as well

**Comment by prasanthmk82** [comment]
> @prasanthmk82 can you check phone number again? I add some log info.
> https://github.com/AlexxIT/SonoffLAN/tree/phone
> Your phone number starts with "+"?

No my phone number has only 10 digit

**Comment by prasanthmk82** [comment]
> @prasanthmk82 can you check phone number again? I add some log info.
> https://github.com/AlexxIT/SonoffLAN/tree/phone
> Your phone number starts with "+"?

Ok now able to login,. but no devices appeared. Seems like didnt got the device key

2020-02-13 13:55:17 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-02-13 13:55:17 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-02-13 13:55:20 ERROR (SyncWorker_19) [custom_components.sonoff.utils] Login with phone error: {'error': 400, 'msg': 'params is error'}
2020-02-13 13:55:20 WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] No devicekey for device 1000a4ea15
2020-02-13 13:55:20 WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] No devicekey for device 10009bcc1f
2020-02-13 13:55:20 WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] No devicekey for device 1000a42619
2020-02-13 13:55:20 WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] No devicekey for device 1000a4f10c
2020-02-13 13:55:20 WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] No devicekey for device 10009c052d
2020-02-13 13:55:20 WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] No devicekey for device 100041a797
2020-02-13 13:55:20 WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] No devicekey for device 1000540327
2020-02-13 13:55:20 WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] No devicekey for device 1000a55f41
2020-02-13 13:55:20 WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] No devicekey for device 1000a4347a
2020-02-13 13:55:20 WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] No devicekey for device 10003c139c
2020-02-13 13:55:20 WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] No devicekey for device 10003c14a4
2020-02-13 13:55:25 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2020-02-13 13:55:26 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2020-02-13 13:55:26 WARNING (MainThread) [aiohue.util] Received unexpected bridge id: 93eadbeef13
2020-02-13 13:55:40 ERROR (MainThread) [hacs] Validation for DSorlov/hasl-platform failed with GitHub returned 404 for https://api.github.com/repos/DSorlov/hasl-platform/git/trees/master.

**Comment by prasanthmk82** [comment]
Please help with RF bridge issue. is it supposed to get 4 press commands instead of one?

**Comment by prasanthmk82** [comment]
here is the debug log

https://paste.ubuntu.com/p/Htwj3hGDBT/

**Comment by AlexxIT** [comment]
@prasanthmk82 You receive event 4 times or receive 1 event with command=4?

**Comment by prasanthmk82** [comment]
I received event 4 times

**Comment by dawiduniec** [comment]
I'm getting:

Please, send this device type to developer: th_plug
10:00 custom_components/sonoff/__init__.py (WARNING)

**Comment by AlexxIT** [comment]
@dawiduniec thanks. It's Sonoff TH?

**Comment by AlexxIT** [comment]
@prasanthmk82 please show debug log when button pressed. Need lines with `State:`.

**Comment by AlexxIT** [comment]
@prasanthmk82 the phone number should lead with region number, `+8612345678901` for example.

**Comment by prasanthmk82** [comment]
ok will try that and report

**Comment by prasanthmk82** [comment]
Still the same error even after giving country code

https://paste.ubuntu.com/p/2Gqn82rFRT/

**Comment by prasanthmk82** [comment]
Here is the debug log for Sonoff remote press

https://paste.ubuntu.com/p/wBS5VJs5Zy/

Also the consumption for Pow R3 not available. That means the current, voltage and Power sensor entities are not available

**Comment by AlexxIT** [comment]
@prasanthmk82 
I see the problem, but did not face it on my rf bridge.
Is the latest firmware on your device?
Do you have other rf remotes? They have the same problem?

**Comment by ebattulga** [comment]
@prasanthmk82 Hey, How to entered phone number on username field. i'm trying to add my phone number with and without country code, with + sign and anything won't work.

**Comment by prasanthmk82** [comment]
> @prasanthmk82
> I see the problem, but did not face it on my rf bridge.
> Is the latest firmware on your device?
> Do you have other rf remotes? They have the same problem?

I have one remote, but another one is already tasmotized.

**Comment by prasanthmk82** [comment]
> @prasanthmk82 Hey, How to entered phone number on username field. i'm trying to add my phone number with and without country code, with + sign and anything won't work.

You need to use this component and add manually in custom_components folder.
https://github.com/AlexxIT/SonoffLAN/tree/phone

i even tried with and without country code, both got logged in, but the entoties didnt show in HA

**Comment by AlexxIT** [comment]
@prasanthmk82 Peterburga component support RF Bridge?
I mean other buttons

**Comment by prasanthmk82** [comment]
> @prasanthmk82 Peterburga component support RF Bridge?
> I mean other RF 433 remotes (buttons), not other bridge.

Sorry i misunderstood. Yes. I have tried 2 remotes already. 
Yes Peterburgas component support RF bridge

**Comment by prasanthmk82** [comment]
> @prasanthmk82 Hey, How to entered phone number on username field. i'm trying to add my phone number with and without country code, with + sign and anything won't work.

were u able to get ur devices in entity?

**Comment by prasanthmk82** [comment]
@AlexxIT any update?

**Comment by AlexxIT** [comment]
@prasanthmk82 all 3 RF remote generate 4 events with each button?

**Comment by AlexxIT** [comment]
@prasanthmk82 what `api_region` you set in Peterburgas component? What is the prefix of your phone number?

**Comment by prasanthmk82** [comment]
> @prasanthmk82 all 3 RF remote generate 4 events with each button?

Yes. one button press creates 4 events

**Comment by prasanthmk82** [comment]
> @prasanthmk82 what `api_region` you set in Peterburgas component? What is the prefix of your phone number?

as (Asia)

**Comment by AlexxIT** [comment]
@prasanthmk82 try latest version:
https://github.com/AlexxIT/SonoffLAN/tree/phone

**Comment by prasanthmk82** [comment]
> @prasanthmk82 try latest version:
> https://github.com/AlexxIT/SonoffLAN/tree/phone

Still the same. Able to login but the devices does not show as entity. Same error saying no device key.
Also, same 4 events generated for each button press in RF remote

https://paste.ubuntu.com/p/yKpbGjzc5f/

**Comment by prasanthmk82** [comment]
Login in through phone number is not important since we can log in using an email ID and share the components from the phone number login to ID with email. 
But RF remote sending 4 events in a single press is a bigger issue

**Comment by AlexxIT** [comment]
@prasanthmk82 all your devices resend updates 4 times. I think the router does it. But I will fix it.

**Comment by prasanthmk82** [comment]
The router doesnt do that. Since it first occured in my friend's wifi and then I changed it to my wifi. Both have same issue

**Comment by AlexxIT** [comment]
@prasanthmk82 several events fixed in latest update. Check it.

**Comment by prasanthmk82** [comment]
> @prasanthmk82 several events fixed in latest update. Check it.

As mentioned above I have tried latest component with bith RF bridge and phone number username and both of them still doesn't work

**Comment by prasanthmk82** [comment]
> @prasanthmk82 several events fixed in latest update. Check it.

RF remote multiple event issue fixed. But login through phone number issue is still there. Hope it will be fixed soon.  Thank you so much

**Comment by prasanthmk82** [comment]
Ok. I have got the phone login working. 

I have changed here eu to as

    else:
        region = 'as'
        params = _params(email=username, password=password)

Now only thing remaining is Pow R2 entities.

**Comment by gsdovali** [comment]
> @gsdovali you need use automation with `sonoff.remote` event
> 
> ```
> automation:
> - alias: Test RF
>   trigger:
>     platform: event
>     event_type: sonoff.remote
>     event_data:
>       command: 0
>   action:
>     service: homeassistant.toggle
>     entity_id: remote.sonoff_1000abcdefg
> ```

ok, I created the automation, but nothing happens; what should I get when pressing a button?

**Comment by prasanthmk82** [comment]
> > @gsdovali you need use automation with `sonoff.remote` event
> > ```
> > automation:
> > - alias: Test RF
> >   trigger:
> >     platform: event
> >     event_type: sonoff.remote
> >     event_data:
> >       command: 0
> >   action:
> >     service: homeassistant.toggle
> >     entity_id: remote.sonoff_1000abcdefg
> > ```
> 
> ok, I created the automation, but nothing happens; what should I get when pressing a button?

That is just an example. U should get command with a number. And that number can be used to create automation.

**Comment by prasanthmk82** [comment]
> Ok. I have got the phone login working.
> 
> I have changed here eu to as in utils.py file in this link
> https://github.com/AlexxIT/SonoffLAN/tree/phone
> 
> ```
> else:
>     region = 'as'
>     params = _params(email=username, password=password)
> ```
> 
> Now only thing remaining is Pow R2 sensor entities.

@AlexxIT Please update the component to enable it phone login. I have shared how i got success as mentioned. may be that can help?

**Comment by AlexxIT** [comment]
@prasanthmk82 your code changed email login, not phone login...

**Comment by AlexxIT** [comment]
If someone sends me a phone and password, I can debug this function. I can’t create an account over the phone in my country.
For example [here](https://community.home-assistant.io/u/AlexxIT) in a private message or in Telegram.

**Comment by AlexxIT** [comment]
@prasanthmk82 Pow sensors will not appear themselves. They can be displayed through the template sensor. An example is in the readme.

**Comment by prasanthmk82** [comment]
> @prasanthmk82 your code changed email login, not phone login...

But after using this. I am able to get all my entities in phone login to appear in HA.

**Comment by AlexxIT** [comment]
Support login with phone number added in latest version
