### ISSUE TITLE
'version' key missing in the manifest 

### ISSUE THREAD

**Issue by chemelli74** [AlexxIT/SonoffLAN#374]
Current dev build of HA shows this warning:

`2021-02-10 09:31:51 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'sonoff'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'sonoff'
`
Should be easy to fix ;-)

Thank you,

Simone

**Comment by kierenblack** [comment]
I hope this is fixed soon before HA makes it compulsary.

**Comment by Verguldebarman** [comment]
More info can be found here: https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes

see **Custom integrations: Version warning**:

> Custom integrations now require a version key in their manifest file, this also means that all custom integrations now require a manifest file.
> 
> If you are using a legacy custom integration like custom_components/awesome.py this now needs to move to custom_components/awesome/init.py so you can add custom_components/awesome/manifest.json to it.
> 
> For more information about integration, manifests have a look here: https://developers.home-assistant.io/docs/creating_integration_manifest
> 
> For now, this will create a warning on startup. But this will eventually be blocked from loading if it’s missing a version in the manifest.

**Comment by AlexxIT** [comment]
Fixed in latest release

**Comment by loveisfoss** [comment]
Hey, the sonoff integration that i have added manually to home assistant is not being loaded after an upgrade 1-2 weeks ago. I use home assistant on docker and I have just copied the sonoff files to the custom_compontents folder, used to work without problems earlier in time, I would just get the warning that at some point it would stop working.

```
2021-06-13 11:00:14 ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'sonoff' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details 
```
The manifest file of sonoff is:
```
{
  "domain": "sonoff",
  "name": "Sonoff",
  "documentation": "https://github.com/AlexxIT/SonoffLAN",
  "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
  "codeowners": ["@AlexxIT"],
  "dependencies": ["http", "zeroconf"],
  "requirements": ["pycryptodome>=3.6.6"],
  "version": "v2.4.6",
  "iot_class": "local_push"
}
```

**Comment by Ghostbuster64** [comment]
STILL NOT FIXED!
" ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'sonoff' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details"

**Comment by chemelli74** [comment]
Please check my reply in the issue you opened, #548 

Simone
