### ISSUE TITLE
V3.0rc1 all entities become Unavailable

### ISSUE THREAD

**Issue by VITCHEPF** [AlexxIT/SonoffLAN#762]
When installing V3.0rc1 all entities become "Unavailable".
They are all connected to the router, but unavailable in HA.

When downgrading to V2.4.7 everything works correctly again.

![Screenshot_20220423-222645](https://user-images.githubusercontent.com/73760504/164952231-9202a13f-426e-44be-a4ea-82ace6366f9b.jpg)

SONOFF ENTITIES

![Screenshot_20220423-223816](https://user-images.githubusercontent.com/73760504/164952245-eba9e56d-20ca-477e-b5a5-651ea0631e96.jpg)

**Comment by AlexxIT** [comment]
Fixed in next beta-version

**Comment by VITCHEPF** [comment]
I deleted V3.0rc1 and installed V3.0rc2.


The problem persists, all SONOFF entities appear UNAVAILABLE.

When performing the Downgrade to V2.4.7, all Entities work again.

I'm using an Android 11.


Thanks in advance,


Vincenzo


Em dom., 24 de abr. de 2022 02:10, Alex X ***@***.***>
escreveu:

**Comment by AlexxIT** [comment]
You need to provide errors from the Hass log
